### ISSUE TITLE
Feedback at the end if a game is a 'cats-game'

### ISSUE THREAD

**Issue by zurda** [zurda/React-TicTacToe#24]
Feedback if the end of the game is a 'Cats-game': this means all squared are filled but no Tic-Tac-Toe was completed. Should be easy to do. 

Implementation pointers from the Udemy forum (@sselke)

> Just keep currentNumber of squares occupied in your state, and also have a conditional for ticTacToe: true or false. If currentNumber === 9 & ticTacToe === false, then displace a message reflecting the tie game.

**Comment by rileythomp** [comment]
I think I can do this for you. Will try out tonight.

**Comment by zurda** [comment]
Sure thing, @rileythomp !
